name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.101'

    - name: Publish .NET application
      run: dotnet publish -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-app
        path: ./publish

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dotnet-app

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: 18.223.149.26
      run: |
        scp -i $EC2_SSH_KEY -o StrictHostKeyChecking=no -r ./publish/* $EC2_USER@$EC2_HOST:/var/www/myapp/
        ssh -i $EC2_SSH_KEY -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'sudo systemctl restart myapp.service'
