name: Deploy to EC2 via S3 and SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.101' # Specify your .NET version

    - name: Publish .NET application
      run: dotnet publish -c Release -o ./publish

    - name: Upload artifact to S3
      env:
        S3_BUCKET: uzair-microservices-testing # Your S3 bucket name
        COMMIT_SHA: ${{ github.sha }}
      run: |
        zip -r deploy-package-${COMMIT_SHA}.zip ./publish
        aws s3 cp deploy-package.zip s3://$S3_BUCKET/deploy-package.zip

    - name: Deploy to EC2 via SSH
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: 18.223.149.26
        S3_BUCKET: uzair-microservices-testing
        COMMIT_SHA: ${{ github.sha }}
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "wget https://$S3_BUCKET.s3.us-east-2.amazonaws.com/deploy-package-${COMMIT_SHA}.zip -O /tmp/deploy-package.zip"
        ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "unzip -o /tmp/deploy-package.zip -d /var/www/myapp/"
        ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "sudo systemctl restart myapp.service"
