name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Specify your .NET version

    - name: Publish .NET application
      run: dotnet publish -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-app
        path: ./publish

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dotnet-app

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 # Your AWS region

    - name: Deploy to EC2 via SSM
      env:
        INSTANCE_ID: i-02d57b1882b7e5fe9 # Your EC2 instance ID
        S3_BUCKET: uzair-microservices-testing # Your S3 bucket name
      run: |
        zip -r deploy-package.zip ./publish
        aws s3 cp deploy-package.zip s3://$S3_BUCKET/deploy-package.zip
        aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy .NET app" \
          --parameters commands="aws s3 cp s3://$S3_BUCKET/deploy-package.zip /tmp/deploy-package.zip, unzip /tmp/deploy-package.zip -d /var/www/myapp/, sudo systemctl restart myapp.service" \
          --region ${{ secrets.AWS_REGION }}
