name: Deploy Vehicles Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.101'

      - name: Restore dependencies
        run: dotnet restore ./Vehicles.csproj

      - name: Build
        run: dotnet build --configuration Release ./Vehicles.csproj

      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained -o ./publish/vehicles

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli

      - name: Check EB CLI version
        run: eb --version

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
        run: |
          eb init "Microservices POC" -p "64bit Amazon Linux 2023 v3.1.5 running .NET 8" -r "us-east-2"  --no-verify-ssl
          eb use Vehicles-env    
          eb deploy --no-verify-ssl
